global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.41.139:9090','172.31.44.7:9100','172.31.41.118:9100']
